### ISSUE TITLE
64 bit builds in the UFID documentation

### ISSUE THREAD

**Issue by frutiger** [bloomberg/bde-tools#15]
I have sometimes seen mention of `_64` in UFIDs, but the documentation on possible UFIDs does not explicitly mention this.  Is this correct?

**Comment by mversche** [comment]
That is correct, you can find the relevant documentation:
https://github.com/bloomberg/bde-tools/wiki/Waf-Build

Where it describes the UFID option (-t) provieds a link to:
https://github.com/bloomberg/bde-tools/wiki/BDE-Style-Repository#ufid

Which provides a list of ufid flags (including 64).

**Comment by frutiger** [comment]
Sorry, I must have just missed it when reading it!
