### ISSUE TITLE
Not building applications

### ISSUE THREAD

**Issue by hervebronnimann** [bloomberg/bde-tools#19]
I created a workspace with my libraries, a top-level applications directory, and waf configure only reports my UORs for the groups, but not the applications.  Any hints?

**Comment by che2** [comment]
First, make sure that you have an empty  .bdeworkspaceconfig file in the top-level workspace directory. 
If that doesn't work, please provide the directory structure of your workspace and the output of waf configure.

**Comment by hervebronnimann** [comment]
Firstly, I'm not really using a workspace, my directory structure is:

./applications/{a1,a2,a3,...}
./groups/{mbe,mae,ser}
wscript

Without the .bdeworkspaceconfig, but the default .bdelayoutconfig (copied over from bde-tools/share/sample.config/) it find the 3 uors (mbe, mae, and ser) and the 56 components.  With the empty  .bdeworkspaceconfig file as you suggested, it finds 0 0 0.

**Comment by hervebronnimann** [comment]
I also made sure each application has the correct package/a1.{mem,dep} substructure.

**Comment by che2** [comment]
That's strange, it should have found it. Can you copy the output of a "tree" operation in your "applications" directory?

**Comment by hervebronnimann** [comment]
Thanks for suggesting tree, it showed me clearly that I had not added the *mem (or they were removed, b/c they are empty anyway).  I am seeing stand-alone UORs now!

Thanks!
