### ISSUE TITLE
waf vs CMake: what's recommended?

### ISSUE THREAD

**Issue by EricHripko** [bloomberg/bde-tools#29]
In issue #26 it is mentioned that waf is getting replaced with CMake.
Has this been done? And if it was, is this the recommended way to build bde?

**Comment by mversche** [comment]
Our internal production builds are still produced with `waf`, though we are in the last stages of verifying our `CMake` build for production use.

**Comment by osubboo** [comment]
Cmake-based build system will eventually replace waf. Will be announced.
Recommended is still waf.

**Comment by EricHripko** [comment]
Makes sense - thank you for the explanation 👍
