### ISSUE TITLE
Cannot Create Debug Build 

### ISSUE THREAD

**Issue by Stackingit** [bloomberg/bde-tools#3]
Given the following waf config

    # waf 1.7.15 (abi 98, python 20708f0 on win32)
    # using E:\BDE\bde-tools-master\bin\waf configure --build-type=debug

And a quick check on one of the produced libs

    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC>dumpbin /directives E:\BDE
    \bde-master\build\groups\bsl\bsls\bsls.lib | find /i "/FailIfMismatch"
    /FAILIFMISMATCH:"_MSC_VER=1800"
    /FAILIFMISMATCH:"_ITERATOR_DEBUG_LEVEL=0"
    /FAILIFMISMATCH:"RuntimeLibrary=MT_StaticRelease"

Which results in the following errors when trying to link in the "debug" version for a debug project

    Error	1	error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in bsls_assert.t.obj
    Error	2	error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in bsls_assert.t.obj

And the following waf environment setup

	----------------------------------------
	os_type
	windows
	----------------------------------------
	os_name
	windows_nt
	----------------------------------------
	cpu_type
	x86
	----------------------------------------
	os_ver
	6.1
	----------------------------------------
	comp_type
	cl
	----------------------------------------
	comp_ver
	18.00
	----------------------------------------
	uplid
	windows-windows_nt-x86-6.1-cl-18.00
	----------------------------------------
	ufid
	dbg_exc_mt
	----------------------------------------
	prefix
	C:\users\stephenb\appdata\local\temp
	----------------------------------------
	Loading BDE metadata
	ok
	----------------------------------------
	Evaluating options for 'bsl'
	ok
	----------------------------------------
	Evaluating options for 'bdl'
	ok
	----------------------------------------
	Saving configuration
	ok

**Comment by che2** [comment]
After some consideration. We decided to not add support for setting iterator debug level in the build system as to not overly complicate it. We will reconsider if more people encounter this issue.
