### ISSUE TITLE
BDE tools requires exactly python3.8 which may not be available on the build machine

### ISSUE THREAD

**Issue by mattrm456** [bloomberg/bde-tools#41]
Many python scripts have a shebang line `#!/usr/bin/env python3.8` which requires exactly python 3.8 to be installed on the build machine. These tools should accept any suitable python version. In similar situations I've resolved this by supplying shell scripts (and .cmd files, for Windows users) which proxy the execution of the .py scripts by first manually finding a suitable python then executing the script directly using that python executable (this bypasses the shebang line). But, I'll leave the solution up to the maintainers of this repository.

1. Install BDE tools on any machine that does not have python 3.8 available, or in any case does not have `python3.8` found on the `PATH`
2. Run `bde_build_env.py`, `bde_runtest.py`, `cmake_build.py` or any python script that contains the shebang line `#!/usr/bin/env python3.8`
3. See error: "env: python3.8: No such file or directory"

The behavior I expect for these tools is to find any suitable python version on the machine, simply by the user having place one on the `PATH`, and to automatically use that version. It is a bit unreasonable to require users to install exactly python 3.8.

**Environment:**
 - Darwin G7WH7WFVKV 21.6.0 Darwin Kernel Version 21.6.0

**Comment by mversche** [comment]
We are actually performing a major overhaul of the build system.  I believe the newer build system addresses this concern,  It's available, we just haven't updated our documentaiton to point to it.

Could you try instead:

```
eval `bbs_build_env`
bbs_build configure
bbs_build build --test=run
```

The options for configuring the compiler are slightly different (`bbs_build_env --help` )

**Comment by mattrm456** [comment]
The `bbs_build.py` script also has the shebang line `#!/usr/bin/env python3.8`, at least on the master branch.

**Comment by osubboo** [comment]
do not run .py files for new build system

**Comment by osubboo** [comment]
and use main branch, not master

**Comment by mattrm456** [comment]
This issue is not present in `bbs_build` on the `main` branch. But see https://github.com/bloomberg/bde-tools/issues/42.
