### ISSUE TITLE
BDE tools requires 'realpath' which is not necessarily installed nor really needed

### ISSUE THREAD

**Issue by mattrm456** [bloomberg/bde-tools#42]
The wrapper scripts such as `bbs_build_env` call `realpath` to get the absolute, real path to the current script file. The `realpath` executable is not necessarily installed on a build machine (it is not present by default on Darwin, for example) nor is it really needed, at least in its purpose in these wrapper scripts. 

Instead, consider doing some shell magic instead to get the absolute path to the script's directory:
```
DIRECTORY=$(dirname ${0})
if [[ -n ${DIRECTORY##/*} ]]; then
    DIRECTORY=${PWD}/${DIRECTORY#.}
fi
DIRECTORY=${DIRECTORY%/}
```
Then form the full absolute path to the script:
```
SCRIPT=${DIRECTORY}/$(basename ${0})
```
I think this works with just a POSIX shell. 

**To Reproduce**
1. Run `bbs_build_env` on a machine without the `realpath` utility
2. bbs_build_env: line 5: realpath: command not found 

**Environment:**
 - Darwin G7WH7WFVKV 21.6.0 Darwin Kernel Version 21.6.0

**Comment by mversche** [comment]
Thanks for the suggest.  Will investigate.  Internal ticket tracking  171003977

**Comment by osubboo** [comment]
Done.
